In [150]:
import numpy as np
import pandas as pd

In [151]:
pd.set_option('display.max_columns', 0)
pd.set_option('display.max_rows', 500)

df_loan = pd.read_csv('loan.csv', low_memory=False)

In [152]:
df_loan.head()

        id  member_id  loan_amnt  funded_amnt  funded_amnt_inv        term     ...       max_bal_bc  all_util total_rev_hi_lim inq_fi total_cu_tl inq_last_12m
0  1077501    1296599     5000.0       5000.0           4975.0   36 months     ...              NaN       NaN              NaN    NaN         NaN          NaN
1  1077430    1314167     2500.0       2500.0           2500.0   60 months     ...              NaN       NaN              NaN    NaN         NaN          NaN
2  1077175    1313524     2400.0       2400.0           2400.0   36 months     ...              NaN       NaN              NaN    NaN         NaN          NaN
3  1076863    1277178    10000.0      10000.0          10000.0   36 months     ...              NaN       NaN              NaN    NaN         NaN          NaN
4  1075358    1311748     3000.0       3000.0           3000.0   60 months     ...              NaN       NaN              NaN    NaN         NaN          NaN

[5 rows x 74 columns]

In [153]:
good_loan =  len(df_loan[(df_loan.loan_status == 'Fully Paid') |
                    (df_loan.loan_status == 'Current') | 
                    (df_loan.loan_status == 'Does not meet the credit policy. Status:Fully Paid')])
print ('Good/Bad Loan Ratio: %.2f%%'  % (good_loan/len(df_loan)*100))

Good/Bad Loan Ratio: 91.45%

In [154]:
df_loan.loan_status.value_counts()

Current                                                601779
Fully Paid                                             207723
Charged Off                                             45248
Late (31-120 days)                                      11591
Issued                                                   8460
In Grace Period                                          6253
Late (16-30 days)                                        2357
Does not meet the credit policy. Status:Fully Paid       1988
Default                                                  1219
Does not meet the credit policy. Status:Charged Off       761
Name: loan_status, dtype: int64

In [155]:
df_loan.shape

(887379, 74)

In [156]:
df_loan.drop(['id', 'member_id', 'emp_title','title','url','zip_code','verification_status','home_ownership','issue_d','earliest_cr_line','last_pymnt_d','next_pymnt_d','desc','last_credit_pull_d', ], axis=1, inplace=True)

In [157]:
df_loan.count().sort_values()

dti_joint                         509
annual_inc_joint                  511
verification_status_joint         511
il_util                         18617
mths_since_rcnt_il              20810
open_acc_6m                     21372
open_il_6m                      21372
open_il_12m                     21372
open_il_24m                     21372
total_bal_il                    21372
inq_last_12m                    21372
total_cu_tl                     21372
open_rv_12m                     21372
open_rv_24m                     21372
max_bal_bc                      21372
all_util                        21372
inq_fi                          21372
mths_since_last_record         137053
mths_since_last_major_derog    221703
mths_since_last_delinq         433067
tot_cur_bal                    817103
tot_coll_amt                   817103
total_rev_hi_lim               817103
emp_length                     842554
revol_util                     886877
collections_12_mths_ex_med     887234
pub_rec                        887350
inq_last_6mths                 887350
total_acc                      887350
acc_now_delinq                 887350
delinq_2yrs                    887350
open_acc                       887350
annual_inc                     887375
application_type               887379
policy_code                    887379
loan_amnt                      887379
collection_recovery_fee        887379
funded_amnt                    887379
funded_amnt_inv                887379
term                           887379
int_rate                       887379
installment                    887379
grade                          887379
sub_grade                      887379
loan_status                    887379
pymnt_plan                     887379
purpose                        887379
addr_state                     887379
dti                            887379
revol_bal                      887379
initial_list_status            887379
out_prncp                      887379
out_prncp_inv                  887379
total_pymnt                    887379
total_pymnt_inv                887379
total_rec_int                  887379
total_rec_late_fee             887379
recoveries                     887379
last_pymnt_amnt                887379
total_rec_prncp                887379
dtype: int64

In [158]:
lack_of_data_idx = [x for x in df_loan.count() < 887379*0.2]
df_loan.drop(df_loan.columns[lack_of_data_idx], 1, inplace=True)

In [160]:
df_loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887379 entries, 0 to 887378
Data columns (total 42 columns):
loan_amnt                      887379 non-null float64
funded_amnt                    887379 non-null float64
funded_amnt_inv                887379 non-null float64
term                           887379 non-null object
int_rate                       887379 non-null float64
installment                    887379 non-null float64
grade                          887379 non-null object
sub_grade                      887379 non-null object
emp_length                     842554 non-null object
annual_inc                     887375 non-null float64
loan_status                    887379 non-null object
pymnt_plan                     887379 non-null object
purpose                        887379 non-null object
addr_state                     887379 non-null object
dti                            887379 non-null float64
delinq_2yrs                    887350 non-null float64
inq_last_6mths                 887350 non-null float64
mths_since_last_delinq         433067 non-null float64
open_acc                       887350 non-null float64
pub_rec                        887350 non-null float64
revol_bal                      887379 non-null float64
revol_util                     886877 non-null float64
total_acc                      887350 non-null float64
initial_list_status            887379 non-null object
out_prncp                      887379 non-null float64
out_prncp_inv                  887379 non-null float64
total_pymnt                    887379 non-null float64
total_pymnt_inv                887379 non-null float64
total_rec_prncp                887379 non-null float64
total_rec_int                  887379 non-null float64
total_rec_late_fee             887379 non-null float64
recoveries                     887379 non-null float64
collection_recovery_fee        887379 non-null float64
last_pymnt_amnt                887379 non-null float64
collections_12_mths_ex_med     887234 non-null float64
mths_since_last_major_derog    221703 non-null float64
policy_code                    887379 non-null float64
application_type               887379 non-null object
acc_now_delinq                 887350 non-null float64
tot_coll_amt                   817103 non-null float64
tot_cur_bal                    817103 non-null float64
total_rev_hi_lim               817103 non-null float64
dtypes: float64(32), object(10)
memory usage: 284.3+ MB

In [162]:
print (df_loan.mths_since_last_delinq.min(), df_loan.mths_since_last_delinq.max())
print(df_loan.mths_since_last_delinq.mean())
print(df_loan.mths_since_last_delinq.median())

0.0 188.0
34.06379844227337
31.0

In [163]:
df_loan.mths_since_last_delinq = df_loan.mths_since_last_delinq.fillna(df_loan.mths_since_last_delinq.median())

In [164]:
df_loan.dropna(inplace=True)

In [165]:
df_loan.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 208616 entries, 42538 to 887377
Data columns (total 42 columns):
loan_amnt                      208616 non-null float64
funded_amnt                    208616 non-null float64
funded_amnt_inv                208616 non-null float64
term                           208616 non-null object
int_rate                       208616 non-null float64
installment                    208616 non-null float64
grade                          208616 non-null object
sub_grade                      208616 non-null object
emp_length                     208616 non-null object
annual_inc                     208616 non-null float64
loan_status                    208616 non-null object
pymnt_plan                     208616 non-null object
purpose                        208616 non-null object
addr_state                     208616 non-null object
dti                            208616 non-null float64
delinq_2yrs                    208616 non-null float64
inq_last_6mths                 208616 non-null float64
mths_since_last_delinq         208616 non-null float64
open_acc                       208616 non-null float64
pub_rec                        208616 non-null float64
revol_bal                      208616 non-null float64
revol_util                     208616 non-null float64
total_acc                      208616 non-null float64
initial_list_status            208616 non-null object
out_prncp                      208616 non-null float64
out_prncp_inv                  208616 non-null float64
total_pymnt                    208616 non-null float64
total_pymnt_inv                208616 non-null float64
total_rec_prncp                208616 non-null float64
total_rec_int                  208616 non-null float64
total_rec_late_fee             208616 non-null float64
recoveries                     208616 non-null float64
collection_recovery_fee        208616 non-null float64
last_pymnt_amnt                208616 non-null float64
collections_12_mths_ex_med     208616 non-null float64
mths_since_last_major_derog    208616 non-null float64
policy_code                    208616 non-null float64
application_type               208616 non-null object
acc_now_delinq                 208616 non-null float64
tot_coll_amt                   208616 non-null float64
tot_cur_bal                    208616 non-null float64
total_rev_hi_lim               208616 non-null float64
dtypes: float64(32), object(10)
memory usage: 68.4+ MB

In [166]:
# Calculate Good and Bad Loan Status Ratio
good_loan =  len(df_loan[(df_loan.loan_status == 'Fully Paid') |
                    (df_loan.loan_status == 'Current') | 
                    (df_loan.loan_status == 'Does not meet the credit policy. Status:Fully Paid')])
print ('Good/Bad Loan Ratio: %.2f%%'  % (good_loan/len(df_loan)*100))

Good/Bad Loan Ratio: 92.09%

In [167]:
df_loan['good_loan'] = np.where((df_loan.loan_status == 'Fully Paid') |
                        (df_loan.loan_status == 'Current') | 
                        (df_loan.loan_status == 'Does not meet the credit policy. Status:Fully Paid'), 1, 0)

In [168]:
df_loan.shape

(208616, 43)

In [169]:
columns = ['term', 'grade', 'sub_grade', 'emp_length', 'purpose', 'application_type','addr_state',
           'pymnt_plan', 'initial_list_status']

for col in columns:
    tmp_df = pd.get_dummies(df_loan[col], prefix=col)
    df_loan = pd.concat((df_loan, tmp_df), axis=1)

In [170]:
df_loan.drop(['loan_status',
           'term',
           'grade',
           'sub_grade',
           'emp_length',
           'addr_state',
           'initial_list_status',
           'pymnt_plan',
           'purpose',
           'application_type'], axis=1, inplace=True)

In [171]:
df_loan = df_loan.rename(columns= {'emp_length_< 1 year':'emp_length_lt_1 year',
                         'emp_length_n/a':'emp_length_na'})

In [172]:
df_loan.shape

(208616, 158)

In [173]:
df_loan.head()

       loan_amnt  funded_amnt  funded_amnt_inv  int_rate          ...            pymnt_plan_n  pymnt_plan_y  initial_list_status_f  initial_list_status_w
42538    12000.0      12000.0          12000.0     13.53          ...                       1             0                      0                      1
42539    15000.0      15000.0          15000.0      8.90          ...                       1             0                      0                      1
42543    10000.0      10000.0          10000.0      9.67          ...                       1             0                      1                      0
42544     3000.0       3000.0           3000.0     12.85          ...                       1             0                      1                      0
42547    27600.0      27600.0          27600.0     19.97          ...                       1             0                      1                      0

[5 rows x 158 columns]

In [174]:
from sklearn.model_selection import train_test_split

y = df_loan['good_loan']
X = df_loan.ix[:, df_loan.columns != 'good_loan']

X_train, X_test, y_train, y_test = train_test_split (X, y, test_size=0.2, random_state=44)

D:\Programas_D\Anaconda3\envs\normal\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

In [175]:
print (X_train.shape)
print (X_test.shape)
print (y_train.shape)
print (y_test.shape)

(166892, 157)
(41724, 157)
(166892,)
(41724,)

In [176]:
X.shape

(208616, 157)

In [177]:
import sklearn.metrics as mt
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler, RobustScaler
rob_scaler = RobustScaler()

X_train_R = rob_scaler.fit_transform(X_train)
X_test_R = rob_scaler.transform(X_test)

In [178]:
from sklearn.svm import SVC

In [179]:
# Weighted prediction feature
y_0 = len(y_train[y_train == 0])/len(y_train)
y_1 = 1 - y_0

### Random Forest

In [180]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators = 20)
rf.fit(X_train, y_train)
       
rf_predictions = rf.predict(X_test)

#print(rf.score(X_test, y_test))
scores = cross_val_score(rf, X_test, y_test, cv=5)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)\n" % (scores.mean(), scores.std() * 2))

print(mt.classification_report(y_test, rf_predictions))
print(mt.confusion_matrix(y_test, rf_predictions))

[0.95937687 0.96153385 0.95626123 0.9602157  0.95841323]
Accuracy: 0.96 (+/- 0.00)

             precision    recall  f1-score   support

          0       0.85      0.59      0.70      3240
          1       0.97      0.99      0.98     38484

avg / total       0.96      0.96      0.96     41724

[[ 1913  1327]
 [  331 38153]]

### XGBOOST

In [181]:
from xgboost import XGBClassifier

xgb = XGBClassifier()
xgb.fit(X_train, y_train)

xgb_predictions = xgb.predict(X_test)
                            
#print(xgb.score(X_test, y_test))
scores = cross_val_score(xgb, X_test, y_test, cv=5)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)\n" % (scores.mean(), scores.std() * 2))

print(mt.classification_report(y_test, xgb_predictions))
print(mt.confusion_matrix(y_test, xgb_predictions))

D:\Programas_D\Anaconda3\envs\normal\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Programas_D\Anaconda3\envs\normal\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Programas_D\Anaconda3\envs\normal\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Programas_D\Anaconda3\envs\normal\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Programas_D\Anaconda3\envs\normal\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

[0.96033553 0.96249251 0.95793889 0.96213301 0.95841323]
Accuracy: 0.96 (+/- 0.00)

             precision    recall  f1-score   support

          0       0.89      0.57      0.69      3240
          1       0.96      0.99      0.98     38484

avg / total       0.96      0.96      0.96     41724

[[ 1841  1399]
 [  225 38259]]

D:\Programas_D\Anaconda3\envs\normal\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff: